name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    env:
      BUILD_CONFIG: Release
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
        source-url: https://api.nuget.org/v3/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c $BUILD_CONFIG
    - name: Test
      run: dotnet test --no-build --verbosity normal -c $BUILD_CONFIG
